export const ABORDAGENS = [
  'Gestalt',
  'TCC (Terapia Cognitivo-Comportamental)',
  'Psicanálise',
  'Humanista',
  'Sistêmica',
  'Comportamental',
  'Junguiana',
  'Existencial',
  'Fenomenológica',
  'Psicodrama',
  'Integrativa',
  'Outra',
];

export const PUBLICOS = [
  'LGBTQIA+',
  'Crianças',
  'Adolescentes',
  'Adultos',
  'Idosos',
  'Casais',
  'Famílias',
  'Gestantes',
  'Mulheres em situação de violência',
  'Pessoas com deficiência',
  'Pessoas em luto',
];

export const TEMAS = [
  'Ansiedade',
  'Depressão',
  'Trauma',
  'Luto',
  'Relacionamentos',
  'Violência de Gênero',
  'Violência Doméstica',
  'Autoestima',
  'Estresse',
  'Burnout',
  'Vícios',
  'Transtornos Alimentares',
  'TOC',
  'Identidade de Gênero',
  'Orientação Sexual',
  'Abuso/Negligência',
  'Sexualidade',
  'Carreira e Propósito',
  'Maternidade/Paternidade',
  'Neurodivergência',
];

export const TONS = [
  'Acolhedor',
  'Direto',
  'Reflexivo',
  'Encorajador',
  'Formal',
  'Descontraído',
  'Empático',
  'Firme',
  'Gentil',
];
